#-------PUNTO 1-------
### Ruta raiz con Auth:
GET http://localhost:3000/
x-auth: Pass123

### Ruta raiz sin Auth:
GET http://localhost:3000/

### Ruta Home:
GET http://localhost:3000/home.html
x-auth: Pass123

### Ruta Home sin Auth:
GET http://localhost:3000/home.html

### Ruta Tasks:
GET http://localhost:3000/tasks.html
x-auth: Pass123

### Ruta Tasks sin Auth:
GET http://localhost:3000/tasks.html

#-------PUNTO 2-------
### Consultar usuarios:
GET http://localhost:3000/users?page=1&limit=3
x-auth: admin_auth

### Consultar usuarios sin admin_auth:
GET http://localhost:3000/users?page=1&limit=3
x-auth: Password2

#-------PUNTO 3-------
### Crear Usuario 1 (ID: 1):
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Usuario Uno",
    "email": "uno@prueba.com",
    "password": "Password1",
    "confirm_password": "Password1"
}

### Crear Usuario 2 (ID: 2):
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Usuario Dos",
    "email": "dos@prueba.com",
    "password": "Password2",
    "confirm_password": "Password2"
}

### Crear Usuario 3 (ID: 3):
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Usuario Tres",
    "email": "tres@prueba.com",
    "password": "Password3",
    "confirm_password": "Password3"
}

### Consultar tareas (Usuario ID=1):
GET http://localhost:3000/tasks
x-auth: Password1

### Consultar tareas (Usuario ID=2):
GET http://localhost:3000/tasks
x-auth: Password2

### Consultar tareas (Usuario ID=3):
GET http://localhost:3000/tasks
x-auth: Password3

### Consultar etiquetas (Usuario ID=1):
GET http://localhost:3000/tags
x-auth: Password1

### Consultar etiquetas (Usuario ID=2):
GET http://localhost:3000/tags
x-auth: Password2

### Consultar etiquetas (Usuario ID=3):
GET http://localhost:3000/tags
x-auth: Password3

#-------PUNTO 4-------
### Consulta el usuario con ID=2:
GET http://localhost:3000/users/2
x-auth: Password2

#-------PUNTO 5-------
### Consulta usuarios en la pagina 1, limite 2:
GET http://localhost:3000/users?page=1&limit=2
x-auth: admin_auth

#-------PUNTO 6-------
### Edita tu usuario con el ID: 3 (TU NOMBRE COMPLETO):
PATCH http://localhost:3000/users/3
x-auth: Password3
Content-Type: application/json

{
    "name": "Brandon Michelle Pérez Saldaña"
}

#-------PUNTO 7-------
### Elimina el usuario con el ID 1:
DELETE http://localhost:3000/users/1
x-auth: Password1

### Consulta todos los usuarios para corroborar:
GET http://localhost:3000/users
x-auth: admin_auth

#-------PUNTO 8-------
### Crear Tarea 1 para usuario ID=2:
POST http://localhost:3000/tasks
x-auth: Password2
Content-Type: application/json

{
    "title": "Aprender Node.js",
    "due_date": "2026-04-01",
    "status": "A",
    "tags": []
}

### Crear Tarea 2 para usuario ID=2:
POST http://localhost:3000/tasks
x-auth: Password2
Content-Type: application/json

{
    "title": "Hacer la Práctica 3",
    "due_date": "2026-03-25",
    "status": "A",
    "tags": []
}

### Crear Tarea 3 para usuario ID=2:
POST http://localhost:3000/tasks
x-auth: Password2
Content-Type: application/json

{
    "title": "Estudiar para el examen",
    "due_date": "2026-03-30",
    "status": "F",
    "tags": []
}

#-------PUNTO 9-------
### Consultar la tarea con ID=1:
GET http://localhost:3000/tasks/1
x-auth: Password2

#-------PUNTO 10-------
### Consultar tareas pagina 2, limite 1 (Usuario ID=2):
GET http://localhost:3000/tasks?page=2&limit=1
x-auth: Password2

#-------PUNTO 11-------
### Editar tarea con el ID: 3:
PATCH http://localhost:3000/tasks/3
x-auth: Password2
Content-Type: application/json

{
    "status": "C"
}

#-------PUNTO 12-------
### Eliminar la tarea con el ID 1:
DELETE http://localhost:3000/tasks/1
x-auth: Password2

### Consultar todas las tareas para corroborar (limit=10):
GET http://localhost:3000/tasks
x-auth: Password2

#-------PUNTO 13-------
### Crea Etiqueta 1 para usuario ID=3:
POST http://localhost:3000/tags
x-auth: Password3
Content-Type: application/json

{
    "name": "Escuela",
    "color": "#2ca9e8"
}

### Crea Etiqueta 2 para usuario ID=3:
POST http://localhost:3000/tags
x-auth: Password3
Content-Type: application/json

{
    "name": "Trabajo",
    "color": "#e82c2c"
}

### Crea Etiqueta 3 para usuario ID=3:
POST http://localhost:3000/tags
x-auth: Password3
Content-Type: application/json

{
    "name": "Personal",
    "color": "#2c8e2c"
}

#-------PUNTO 14-------
### Consulta la etiqueta con ID=2:
GET http://localhost:3000/tags/2
x-auth: Password3

#-------PUNTO 15-------
### Consulta etiquetas pagina 1, limite 3 (Usuario ID=3):
GET http://localhost:3000/tags?page=1&limit=3
x-auth: Password3

#-------PUNTO 16-------
### Edita tu etiqueta con el ID: 2:
PATCH http://localhost:3000/tags/2
x-auth: Password3
Content-Type: application/json

{
    "color": "#e3ef39"
}

#-------PUNTO 17-------
### Elimina la etiqueta con el ID 1:
DELETE http://localhost:3000/tags/1
x-auth: Password3

### Consulta todas las etiquetas para corroborar:
GET http://localhost:3000/tags
x-auth: Password3