#-------PUNTO 1-------
### Ruta raiz con Auth:
GET http://localhost:3000/
x-auth: Pass123

### Ruta raiz sin Auth:
GET http://localhost:3000/

### Ruta Home:
GET http://localhost:3000/home.html
x-auth: Pass123

### Ruta Tasks:
GET http://localhost:3000/tasks.html
x-auth: Pass123

#-------PUNTO 2-------
### Usuarios vacio:
GET http://localhost:3000/users?page=1&limit=3
x-auth: admin_auth

#-------PUNTO 3-------
### Crear Usuario 1 (ID: 1):
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Usuario Uno",
    "email": "uno@prueba.com",
    "password": "Password1",
    "confirm_password": "Password1"
}

### Crear Usuario 2 (ID: 2):
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Usuario Dos",
    "email": "dos@prueba.com",
    "password": "Password2",
    "confirm_password": "Password2"
}

### Crear Usuario 3 (ID: 3):
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Usuario Tres",
    "email": "tres@prueba.com",
    "password": "Password3",
    "confirm_password": "Password3"
}

### Tareas vacio:
GET http://localhost:3000/tasks?page=1&limit=5
x-auth: Password2

### Etiquetas vacio:
GET http://localhost:3000/tags?page=1&limit=5
x-auth: Password3

#-------PUNTO 4-------
### Consulta el usuario con ID=2:
GET http://localhost:3000/users/2
x-auth: Password2

#-------PUNTO 5-------
### Consulta usuarios en la pagina 1, limite 2:
GET http://localhost:3000/users?page=1&limit=2
x-auth: admin_auth

#-------PUNTO 6-------
### Edita tu usuario con el ID: 3 (TU NOMBRE COMPLETO):
PATCH http://localhost:3000/users/3
x-auth: Password3
Content-Type: application/json

{
    "name": "Brandon Perez Saldana" 
}

#-------PUNTO 7-------
### Elimina el usuario con el ID 1:
DELETE http://localhost:3000/users/1
x-auth: Password1

### Consulta todos los usuarios para corroborar (limit=10):
GET http://localhost:3000/users?page=1&limit=10
x-auth: admin_auth

#-------PUNTO 8-------
### Crea Tarea 1 para usuario ID=2:
POST http://localhost:3000/tasks
x-auth: Password2
Content-Type: application/json

{
    "title": "Aprender Node.js",
    "due_date": "2026-04-01",
    "status": "A",
    "tags": []
}

### Crea Tarea 2 para usuario ID=2:
POST http://localhost:3000/tasks
x-auth: Password2
Content-Type: application/json

{
    "title": "Hacer la Práctica 3",
    "due_date": "2026-03-25",
    "status": "A",
    "tags": []
}

### Crea Tarea 3 para usuario ID=2:
POST http://localhost:3000/tasks
x-auth: Password2
Content-Type: application/json

{
    "title": "Estudiar para el examen",
    "due_date": "2026-03-30",
    "status": "F",
    "tags": []
}

#-------PUNTO 9-------
### Consulta la tarea con ID=1:
GET http://localhost:3000/tasks/1
x-auth: Password2

#-------PUNTO 10-------
### Consulta tareas pagina 2, limite 1 (Usuario ID=2):
GET http://localhost:3000/tasks?page=2&limit=1
x-auth: Password2

#-------PUNTO 11-------
### Edita tu tarea con el ID: 3:
PATCH http://localhost:3000/tasks/3
x-auth: Password2
Content-Type: application/json

{
    "status": "C"
}

#-------PUNTO 12-------
### Elimina la tarea con el ID 1:
DELETE http://localhost:3000/tasks/1
x-auth: Password2

### Consulta todas las tareas para corroborar (limit=10):
GET http://localhost:3000/tasks?page=1&limit=10
x-auth: Password2

#-------PUNTO 13-------
### Crea Etiqueta 1 para usuario ID=3:
POST http://localhost:3000/tags
x-auth: Password3
Content-Type: application/json

{
    "name": "Escuela",
    "color": "blue"
}

### Crea Etiqueta 2 para usuario ID=3:
POST http://localhost:3000/tags
x-auth: Password3
Content-Type: application/json

{
    "name": "Trabajo",
    "color": "red"
}

### Crea Etiqueta 3 para usuario ID=3:
POST http://localhost:3000/tags
x-auth: Password3
Content-Type: application/json

{
    "name": "Personal",
    "color": "green"
}

#-------PUNTO 14-------
### Consulta la etiqueta con ID=2:
GET http://localhost:3000/tags/2
x-auth: Password3

#-------PUNTO 15-------
### Consulta etiquetas pagina 1, limite 3 (Usuario ID=3):
GET http://localhost:3000/tags?page=1&limit=3
x-auth: Password3

#-------PUNTO 16-------
### Edita tu etiqueta con el ID: 2:
PATCH http://localhost:3000/tags/2
x-auth: Password3
Content-Type: application/json

{
    "color": "yellow"
}

#-------PUNTO 17-------
### Elimina la etiqueta con el ID 1:
DELETE http://localhost:3000/tags/1
x-auth: Password3

### Consulta todas las etiquetas para corroborar (limit=10):
GET http://localhost:3000/tags?page=1&limit=10
x-auth: Password3

#-------PUNTO 18: CASOS DE ERROR Y VALIDACIONES EXTRA-------
### Error: Registro con email repetido (Deberia fallar):
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Usuario Clon",
    "email": "dos@prueba.com",
    "password": "PasswordClon",
    "confirm_password": "PasswordClon"
}

### Error: Registro con contraseñas que no coinciden:
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Usuario Fail",
    "email": "fail@prueba.com",
    "password": "Password123",
    "confirm_password": "Password321"
}

### Error: Consultar usuario ajeno / Contraseña incorrecta (401):
GET http://localhost:3000/users/2
x-auth: Password_Incorrecta

### Error: Intentar acceder a tareas sin header x-auth (401):
GET http://localhost:3000/tasks.html

### Error: Consultar usuario que no existe (404):
GET http://localhost:3000/users/99
x-auth: Password3

### Error: Intentar actualizar usuario sin enviar campos en el body (400):
PATCH http://localhost:3000/users/3
x-auth: Password3
Content-Type: application/json

{}

### Error: Consultar lista de usuarios sin admin_auth (401):
GET http://localhost:3000/users?page=1&limit=3
x-auth: Password2